# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end
  
  # Configuración global
  config.vm.boot_timeout = 600
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  
  config.vm.define :clienteUbuntu do |clienteUbuntu|
    clienteUbuntu.vm.box = "bento/ubuntu-22.04"
    clienteUbuntu.vm.network :private_network, ip: "192.168.100.2"
    clienteUbuntu.vm.hostname = "clienteUbuntu"
    clienteUbuntu.vm.provision "shell", path: "script.sh"
    
    clienteUbuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "clienteUbuntu"
      vb.gui = false
      
      # Configuraciones para evitar errores de CPU
      vb.customize ["modifyvm", :id, "--paravirtprovider", "default"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "off"]
      vb.customize ["modifyvm", :id, "--largepages", "off"]
      vb.customize ["modifyvm", :id, "--vtxvpid", "off"]
      vb.customize ["modifyvm", :id, "--vtxux", "off"]
    end
  end

  config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-22.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
    servidorUbuntu.vm.network "forwarded_port", guest: 8888, host: 8889
    servidorUbuntu.vm.network "forwarded_port", guest: 80, host: 8080
    servidorUbuntu.vm.hostname = "servidorUbuntu"
    servidorUbuntu.vm.provision "shell", path: "script.sh"
    
    servidorUbuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "servidorUbuntu"
      
      # Configuraciones para evitar errores de CPU
      vb.customize ["modifyvm", :id, "--paravirtprovider", "default"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "off"]
      vb.customize ["modifyvm", :id, "--largepages", "off"]
      vb.customize ["modifyvm", :id, "--vtxvpid", "off"]
      vb.customize ["modifyvm", :id, "--vtxux", "off"]
    end
  end

end
